-- Owner-run migration. Startup must never execute this file.
BEGIN;
SELECT pg_advisory_xact_lock(1279873875, 1);
CREATE SCHEMA lms;
REVOKE ALL ON SCHEMA lms FROM PUBLIC;

CREATE TABLE lms.schema_version (
    version integer PRIMARY KEY CHECK (version > 0),
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lms.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name text NOT NULL CHECK (length(trim(display_name)) > 0),
    username text NOT NULL CHECK (username ~ '^[a-z0-9][a-z0-9_.-]{2,31}$'),
    password_hash text NOT NULL CHECK (length(password_hash) > 0),
    role text NOT NULL CHECK (role IN ('member', 'librarian', 'administrator')),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX users_username_uq ON lms.users(lower(username));

CREATE TABLE lms.books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn text,
    title text NOT NULL CHECK (length(trim(title)) > 0),
    author text NOT NULL CHECK (length(trim(author)) > 0),
    publication_year integer NOT NULL CHECK (publication_year BETWEEN 1 AND 9999),
    category text,
    description text,
    created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX books_isbn_uq ON lms.books(lower(isbn));
CREATE UNIQUE INDEX books_identity_uq ON lms.books(lower(title), lower(author), publication_year);
CREATE INDEX books_page_idx ON lms.books(lower(title), id);
CREATE INDEX books_created_idx ON lms.books(created_at, id);

CREATE TABLE lms.book_copies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES lms.books(id) ON DELETE RESTRICT,
    barcode text NOT NULL CHECK (barcode ~ '^[A-Z0-9][A-Z0-9._-]{2,63}$'),
    status text NOT NULL CHECK (status IN ('available', 'on_loan', 'lost', 'damaged', 'withdrawn')),
    created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX book_copies_barcode_uq ON lms.book_copies(lower(barcode));
CREATE INDEX book_copies_book_status_idx ON lms.book_copies(book_id, status, id);

CREATE TABLE lms.reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    book_id bigint NOT NULL REFERENCES lms.books(id) ON DELETE RESTRICT,
    status text NOT NULL CHECK (status IN ('active', 'fulfilled', 'cancelled', 'expired')),
    created_at timestamptz NOT NULL,
    resolved_at timestamptz,
    CHECK ((status = 'active') = (resolved_at IS NULL))
);
CREATE UNIQUE INDEX reservations_active_user_book_uq
    ON lms.reservations(user_id, book_id) WHERE status = 'active';
CREATE INDEX reservations_queue_idx ON lms.reservations(book_id, created_at, id)
    WHERE status = 'active';
CREATE INDEX reservations_user_idx ON lms.reservations(user_id, created_at DESC, id DESC);

CREATE TABLE lms.loans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    book_copy_id bigint NOT NULL REFERENCES lms.book_copies(id) ON DELETE RESTRICT,
    checked_out_at timestamptz NOT NULL,
    due_at timestamptz NOT NULL,
    returned_at timestamptz,
    renewal_count integer NOT NULL DEFAULT 0 CHECK (renewal_count >= 0),
    CHECK (due_at > checked_out_at),
    CHECK (returned_at IS NULL OR returned_at >= checked_out_at)
);
CREATE UNIQUE INDEX loans_active_copy_uq ON lms.loans(book_copy_id) WHERE returned_at IS NULL;
CREATE INDEX loans_user_active_idx ON lms.loans(user_id, due_at) WHERE returned_at IS NULL;
CREATE INDEX loans_user_page_idx ON lms.loans(user_id, checked_out_at DESC, id DESC);
CREATE INDEX loans_copy_history_idx ON lms.loans(book_copy_id);

CREATE TABLE lms.fines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    loan_id bigint UNIQUE REFERENCES lms.loans(id) ON DELETE RESTRICT,
    reason text NOT NULL CHECK (length(trim(reason)) > 0),
    amount_minor bigint NOT NULL CHECK (amount_minor > 0),
    status text NOT NULL CHECK (status IN ('outstanding', 'paid', 'waived')),
    assessed_at timestamptz NOT NULL,
    settled_at timestamptz,
    CHECK ((status = 'outstanding') = (settled_at IS NULL))
);
CREATE INDEX fines_user_page_idx ON lms.fines(user_id, assessed_at DESC, id DESC);
CREATE INDEX fines_outstanding_idx ON lms.fines(user_id) WHERE status = 'outstanding';

CREATE TABLE lms.fine_settlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fine_id bigint NOT NULL UNIQUE REFERENCES lms.fines(id) ON DELETE RESTRICT,
    recorded_by_user_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    kind text NOT NULL CHECK (kind IN ('payment', 'waiver')),
    amount_minor bigint NOT NULL CHECK (amount_minor > 0),
    note text,
    created_at timestamptz NOT NULL
);
CREATE INDEX fine_settlements_actor_idx ON lms.fine_settlements(recorded_by_user_id);

CREATE TABLE lms.book_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    title text NOT NULL CHECK (length(trim(title)) > 0),
    author text NOT NULL CHECK (length(trim(author)) > 0),
    publication_year integer CHECK (publication_year BETWEEN 1 AND 9999),
    status text NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'acquired')),
    created_at timestamptz NOT NULL,
    reviewed_by_user_id bigint REFERENCES lms.users(id) ON DELETE RESTRICT,
    reviewed_at timestamptz,
    review_note text,
    acquired_book_id bigint REFERENCES lms.books(id) ON DELETE RESTRICT,
    acquired_by_user_id bigint REFERENCES lms.users(id) ON DELETE RESTRICT,
    acquired_at timestamptz,
    CHECK ((status = 'pending') = (reviewed_at IS NULL)),
    CHECK ((reviewed_at IS NULL) = (reviewed_by_user_id IS NULL)),
    CHECK ((status = 'acquired') = (acquired_at IS NOT NULL)),
    CHECK ((acquired_at IS NULL) = (acquired_book_id IS NULL)),
    CHECK ((acquired_at IS NULL) = (acquired_by_user_id IS NULL))
);
CREATE UNIQUE INDEX book_requests_pending_uq
    ON lms.book_requests(user_id, lower(title), lower(author), publication_year)
    NULLS NOT DISTINCT WHERE status = 'pending';
CREATE INDEX book_requests_user_page_idx ON lms.book_requests(user_id, created_at DESC, id DESC);
CREATE INDEX book_requests_status_idx ON lms.book_requests(status, created_at, id);
CREATE INDEX book_requests_reviewer_idx ON lms.book_requests(reviewed_by_user_id);
CREATE INDEX book_requests_acquirer_idx ON lms.book_requests(acquired_by_user_id);
CREATE INDEX book_requests_book_idx ON lms.book_requests(acquired_book_id);

CREATE TABLE lms.feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES lms.users(id) ON DELETE SET NULL,
    content text NOT NULL CHECK (length(trim(content)) > 0),
    created_at timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'reviewed', 'archived')),
    reviewed_by_user_id bigint REFERENCES lms.users(id) ON DELETE RESTRICT,
    reviewed_at timestamptz,
    CHECK ((status = 'new') = (reviewed_at IS NULL)),
    CHECK ((reviewed_at IS NULL) = (reviewed_by_user_id IS NULL))
);
CREATE INDEX feedback_user_page_idx ON lms.feedback(user_id, created_at DESC, id DESC);
CREATE INDEX feedback_status_idx ON lms.feedback(status, created_at, id);
CREATE INDEX feedback_reviewer_idx ON lms.feedback(reviewed_by_user_id);

CREATE TABLE lms.idempotency_records (
    actor_id bigint NOT NULL REFERENCES lms.users(id) ON DELETE RESTRICT,
    operation text NOT NULL CHECK (length(operation) BETWEEN 1 AND 100),
    key text NOT NULL CHECK (length(key) BETWEEN 1 AND 200),
    request_hash text NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    response jsonb NOT NULL,
    response_status integer NOT NULL CHECK (response_status BETWEEN 200 AND 499),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (actor_id, operation, key),
    CHECK (expires_at > created_at)
);
CREATE INDEX idempotency_expiry_idx ON lms.idempotency_records(expires_at);

-- RLS denies Data API roles even if grants are accidentally added later.
DO $$
DECLARE item record;
BEGIN
    FOR item IN SELECT tablename FROM pg_tables WHERE schemaname = 'lms' LOOP
        EXECUTE format('ALTER TABLE lms.%I ENABLE ROW LEVEL SECURITY', item.tablename);
    END LOOP;
END $$;
REVOKE ALL ON ALL TABLES IN SCHEMA lms FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA lms FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA lms REVOKE ALL ON TABLES FROM PUBLIC;
INSERT INTO lms.schema_version(version) VALUES (1);
COMMIT;
